# Generated by Django 3.2.16 on 2023-01-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteindex',
            name='pic_saying_3',
            field=models.ImageField(upload_to='ImagIndex/'),
        ),
    ]
