# Generated by Django 3.2.16 on 2023-01-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='orders',
            new_name='order',
        ),
    ]
