# Generated by Django 3.2.16 on 2023-01-31 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0003_meeting_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='uuid',
            field=models.CharField(default=uuid.uuid1, max_length=255, unique=True),
        ),
    ]
