# Generated by Django 3.2.16 on 2023-01-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0005_alter_meeting_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='name',
            new_name='bartment_space',
        ),
    ]
