# Generated by Django 3.2.16 on 2023-01-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0006_rename_name_meeting_bartment_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='bartment_space',
            new_name='name',
        ),
    ]
