# Generated by Django 3.2.16 on 2023-01-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0007_rename_bartment_space_meeting_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='name',
        ),
        migrations.AddField(
            model_name='meeting',
            name='bartment_space',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
