# Generated by Django 3.2.16 on 2023-02-06 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meets', '0008_auto_20230131_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='number',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meet_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
