# Generated by Django 3.2.16 on 2023-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useres', '0002_auto_20230120_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(null=True, upload_to='useres/%y'),
        ),
    ]
