# Generated by Django 3.2.16 on 2023-01-27 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useres', '0003_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=uuid.uuid1, max_length=350, unique=True),
        ),
    ]
